kind: pipeline
type: docker
name: default


steps:
- name: bulid
  image: guangzong/rhugo
  environment:
    SSH_KEY:
      from_secret: ssh_key
  commands:
    - git submodule update --init --recursive
    - R -q -e "blogdown::build_site()"
    # - pwd
    - cd ..
    - echo $SSH_KEY > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
    - git clone git@github.com:chen-gz/chen-gz.github.io.git blog
    - cd blog
    - git checkout gh-page
    - rm -rf *
    - mv src/public/* ./

