kind: pipeline
type: docker
name: default


steps:
- name: deploy
  image: guangzong/rhugo
  commands:
    - git submodule update --init --recursive
    - R -e "blogdown::build_site()"
    - echo "hello world"
  files:
    - public/

